// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package accounts

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateAccountRequest struct {
	FullName             string   `protobuf:"bytes,1,opt,name=fullName,proto3" json:"fullName,omitempty"`
	BirthPlace           string   `protobuf:"bytes,2,opt,name=birthPlace,proto3" json:"birthPlace,omitempty"`
	BirthDate            string   `protobuf:"bytes,3,opt,name=birthDate,proto3" json:"birthDate,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,5,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *CreateAccountRequest) GetBirthPlace() string {
	if m != nil {
		return m.BirthPlace
	}
	return ""
}

func (m *CreateAccountRequest) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

func (m *CreateAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateAccountRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type CreateAccountResponse struct {
	AccountNo            string   `protobuf:"bytes,1,opt,name=accountNo,proto3" json:"accountNo,omitempty"`
	AccountType          string   `protobuf:"bytes,2,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Err                  string   `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetAccountNo() string {
	if m != nil {
		return m.AccountNo
	}
	return ""
}

func (m *CreateAccountResponse) GetAccountType() string {
	if m != nil {
		return m.AccountType
	}
	return ""
}

func (m *CreateAccountResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateAccountRequest)(nil), "accounts.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "accounts.CreateAccountResponse")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0xad, 0x73, 0xb2, 0x1d, 0x99, 0xc8, 0x61, 0x42, 0x18, 0x32, 0x47, 0xaf, 0xbc, 0xea,
	0x85, 0x3e, 0x81, 0xe8, 0x75, 0x91, 0xea, 0x0b, 0xa4, 0xf1, 0xc8, 0x02, 0x69, 0x13, 0xf3, 0x47,
	0xf0, 0x8d, 0x7c, 0x4c, 0x69, 0x9a, 0xda, 0x2a, 0xee, 0x2e, 0xdf, 0xef, 0x83, 0x9c, 0x5f, 0x4e,
	0x60, 0xc5, 0x85, 0xd0, 0xa1, 0xf5, 0x85, 0xb1, 0xda, 0x6b, 0x5c, 0xa4, 0xe8, 0xf2, 0xaf, 0x0c,
	0xd6, 0x0f, 0x96, 0xb8, 0xa7, 0xfb, 0x1e, 0x55, 0xf4, 0x1e, 0xc8, 0x79, 0xdc, 0xc0, 0xe2, 0x2d,
	0x28, 0x55, 0xf2, 0x86, 0x58, 0xb6, 0xcb, 0x6e, 0x96, 0xd5, 0x4f, 0xc6, 0x2d, 0x40, 0x2d, 0xad,
	0xdf, 0x3f, 0x29, 0x2e, 0x88, 0x1d, 0xc7, 0x76, 0x42, 0xf0, 0x0a, 0x96, 0x31, 0x3d, 0x72, 0x4f,
	0x6c, 0x16, 0xeb, 0x11, 0xe0, 0x1a, 0xe6, 0xd4, 0x70, 0xa9, 0xd8, 0x49, 0x6c, 0xfa, 0x80, 0x3b,
	0x38, 0x33, 0x7b, 0xdd, 0x52, 0x19, 0x9a, 0x9a, 0x2c, 0x9b, 0xc7, 0x6e, 0x8a, 0x72, 0x09, 0x97,
	0x7f, 0x4c, 0x9d, 0xd1, 0xad, 0x8b, 0xe3, 0xd2, 0x7b, 0x4a, 0x9d, 0x5c, 0x47, 0xd0, 0x5d, 0x9c,
	0xc2, 0xcb, 0xa7, 0x19, 0x6c, 0xa7, 0x08, 0x2f, 0x60, 0x46, 0xd6, 0x26, 0xd1, 0xee, 0x78, 0xfb,
	0x0a, 0xe7, 0x69, 0xc8, 0x33, 0xd9, 0x0f, 0x29, 0x08, 0x2b, 0x58, 0xfd, 0x1a, 0x8e, 0xdb, 0x62,
	0xd8, 0x61, 0xf1, 0xdf, 0xfe, 0x36, 0xd7, 0x07, 0xfb, 0xde, 0x3a, 0x3f, 0xaa, 0x4f, 0xe3, 0x67,
	0xdc, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x9e, 0x1b, 0xd0, 0x9d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountService/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
}

// UnimplementedAccountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (*UnimplementedAccountServiceServer) CreateAccount(ctx context.Context, req *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountService/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "accounts.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _AccountService_CreateAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
